-- InstaDown Pro Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  downloads integer not null default 0,
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table if not exists public.download_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  url text not null,
  media_type text not null default 'video',
  title text,
  downloaded_at timestamptz not null default now()
);

create index if not exists download_history_user_id_idx on public.download_history(user_id);
create index if not exists download_history_downloaded_at_idx on public.download_history(downloaded_at desc);

alter table public.users enable row level security;
alter table public.download_history enable row level security;

drop policy if exists "Users can view their own profile" on public.users;
create policy "Users can view their own profile"
  on public.users for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.users;
create policy "Users can update their own profile"
  on public.users for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can view their own download history" on public.download_history;
create policy "Users can view their own download history"
  on public.download_history for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own download history" on public.download_history;
create policy "Users can insert their own download history"
  on public.download_history for insert
  to authenticated
  with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture')
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.increment_download_count(target_user_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.users set downloads = downloads + 1 where id = target_user_id;
$$;

grant execute on function public.increment_download_count(uuid) to service_role;
